# Generated by Django 6.0.4 on 2026-04-27 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscricao',
                'verbose_name_plural': 'Inscricoes',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='Nome completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20, verbose_name='Genero')),
                ('full_address', models.TextField(verbose_name='Endereco completo')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone com codigo da sua cidade')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('identity_document', models.CharField(max_length=40, verbose_name='Documento de Identidade')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('guardian_name', models.CharField(blank=True, max_length=180, verbose_name='Nome do responsavel')),
                ('guardian_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone do responsavel')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('medication_in_use', models.TextField(blank=True, verbose_name='Medicamento em uso')),
                ('special_notes', models.TextField(blank=True, verbose_name='Observacoes especiais')),
                ('work_health', models.BooleanField(default=False, verbose_name='Saude')),
                ('work_education', models.BooleanField(default=False, verbose_name='Educacao')),
                ('work_general_help', models.BooleanField(default=False, verbose_name='Auxilio geral')),
                ('work_evangelism', models.BooleanField(default=False, verbose_name='Evangelismo')),
                ('education', models.CharField(blank=True, max_length=180, verbose_name='Qual a sua formacao')),
                ('wants_to_participate', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='sim', max_length=3, verbose_name='Desejo participar voluntariamente da Missao Andrews')),
                ('understands_no_payment', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='sim', max_length=3, verbose_name='Compreendo que atividades desenvolvidas sao sem remuneracao')),
                ('aware_pays_tickets', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='sim', max_length=3, verbose_name='Estou ciente que devo pagar minhas passagens aereas')),
                ('aware_pays_project_fee', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='sim', max_length=3, verbose_name='Estou ciente que devo pagar a taxa de participacao do projeto')),
                ('aware_documents_vaccines', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='sim', max_length=3, verbose_name='Estou ciente que meus documentos e vacinas devem estar em dia')),
                ('aware_non_refundable_fee', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], default='sim', max_length=3, verbose_name='Estou ciente que o valor da taxa de inscricao e nao-reembolsavel')),
                ('city_and_date', models.CharField(blank=True, max_length=120, verbose_name='Cidade e Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='accounts.registration')),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
            },
        ),
    ]
