# Generated by Django 6.0.4 on 2026-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(max_length=120, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('transaction_date', models.DateField(verbose_name='Data')),
                ('receipt', models.FileField(blank=True, upload_to='comprovantes/', verbose_name='Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lancamento financeiro',
                'verbose_name_plural': 'Lancamentos financeiros',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
