# Generated by Django 6.0.4 on 2026-05-09 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_financialtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_registrations', models.BooleanField(default=False, verbose_name='Ver inscritos')),
                ('can_manage_financial', models.BooleanField(default=False, verbose_name='Acessar financeiro')),
                ('can_manage_permissions', models.BooleanField(default=False, verbose_name='Gerenciar permissoes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissao do painel',
                'verbose_name_plural': 'Permissoes do painel',
            },
        ),
    ]
