# Generated by Django 6.0.4 on 2026-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_panelpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='insurance_policy_document',
            field=models.FileField(blank=True, upload_to='documentos/apolices/', verbose_name='Apolice de seguro assinada'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='signed_registration_document',
            field=models.FileField(blank=True, upload_to='documentos/fichas_assinadas/', verbose_name='Ficha de inscricao assinada'),
        ),
    ]
