# Generated by Django 6.0.4 on 2026-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_volunteer_insurance_policy_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='aware_documents_vaccines',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], max_length=3, verbose_name='Estou ciente que meus documentos e vacinas devem estar em dia'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_non_refundable_fee',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], max_length=3, verbose_name='Estou ciente que o valor da taxa de inscricao e nao-reembolsavel'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_pays_project_fee',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], max_length=3, verbose_name='Estou ciente que devo pagar a taxa de participacao do projeto'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_pays_tickets',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], max_length=3, verbose_name='Estou ciente que devo pagar minhas passagens aereas'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='understands_no_payment',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], max_length=3, verbose_name='Compreendo que atividades desenvolvidas sao sem remuneracao'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='wants_to_participate',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao')], max_length=3, verbose_name='Desejo participar voluntariamente da Missao Andrews'),
        ),
    ]
