# Generated by Django 6.0.4 on 2026-05-09 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_volunteer_aware_documents_vaccines_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('participacao', 'Taxa de participacao'), ('cestas', 'Doacao solidaria - 5 cestas basicas')], max_length=20, verbose_name='Tipo de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('receipt', models.FileField(blank=True, upload_to='comprovantes_missionarios/', verbose_name='Comprovante')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Conferido pelo financeiro')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conferido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_missionary_payments', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.volunteer')),
            ],
            options={
                'verbose_name': 'Pagamento de missionario',
                'verbose_name_plural': 'Pagamentos de missionarios',
                'ordering': ['volunteer__full_name', 'payment_type'],
                'unique_together': {('volunteer', 'payment_type')},
            },
        ),
    ]
