# Generated by Django 6.0.4 on 2026-05-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_missionarypayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Lançamento financeiro', 'verbose_name_plural': 'Lançamentos financeiros'},
        ),
        migrations.AlterModelOptions(
            name='missionarypayment',
            options={'ordering': ['volunteer__full_name', 'payment_type'], 'verbose_name': 'Pagamento de missionário', 'verbose_name_plural': 'Pagamentos de missionários'},
        ),
        migrations.AlterModelOptions(
            name='panelpermission',
            options={'verbose_name': 'Permissão do painel', 'verbose_name_plural': 'Permissões do painel'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='missionarypayment',
            name='payment_type',
            field=models.CharField(choices=[('participacao', 'Taxa de participação'), ('cestas', 'Doação solidária - 5 cestas básicas')], max_length=20, verbose_name='Tipo de pagamento'),
        ),
        migrations.AlterField(
            model_name='panelpermission',
            name='can_manage_permissions',
            field=models.BooleanField(default=False, verbose_name='Gerenciar permissões'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_documents_vaccines',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Estou ciente que meus documentos e vacinas devem estar em dia'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_non_refundable_fee',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Estou ciente que o valor da taxa de inscrição é não-reembolsável'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_pays_project_fee',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Estou ciente que devo pagar a taxa de participação do projeto'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aware_pays_tickets',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Estou ciente que devo pagar minhas passagens aéreas'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='education',
            field=models.CharField(blank=True, max_length=180, verbose_name='Qual a sua formação'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='full_address',
            field=models.TextField(verbose_name='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome do responsável'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do responsável'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='insurance_policy_document',
            field=models.FileField(blank=True, upload_to='documentos/apolices/', verbose_name='Apólice de seguro assinada'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefone com código da sua cidade'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='signed_registration_document',
            field=models.FileField(blank=True, upload_to='documentos/fichas_assinadas/', verbose_name='Ficha de inscrição assinada'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='special_notes',
            field=models.TextField(blank=True, verbose_name='Observações especiais'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='understands_no_payment',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Compreendo que atividades desenvolvidas são sem remuneração'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='wants_to_participate',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Desejo participar voluntariamente da Missão Andrews'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='work_education',
            field=models.BooleanField(default=False, verbose_name='Educação'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='work_general_help',
            field=models.BooleanField(default=False, verbose_name='Auxílio geral'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='work_health',
            field=models.BooleanField(default=False, verbose_name='Saúde'),
        ),
    ]
