# Generated by Django 6.0.4 on 2026-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_financialtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='agrees_guidelines',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Concordo em seguir as diretrizes, normas e regulamentos da viagem e da missão'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='authorizes_image_use',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Autorizo o uso de minha imagem para fins institucionais, educativos e de divulgação'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='declares_true_information',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Declaro que as informações acima são verdadeiras'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome completo do contato de emergência'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do contato de emergência'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=80, verbose_name='Parentesco do contato de emergência'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='food_restrictions',
            field=models.TextField(blank=True, verbose_name='Qual(is) restrição(ões) alimentar(es)?'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='has_allergies',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Possui alguma alergia?'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='has_continuous_medication',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Faz uso de medicamentos contínuos?'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='has_food_restriction',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Possui alguma restrição alimentar?'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='other_skills',
            field=models.TextField(blank=True, verbose_name='Outras habilidades que possam contribuir para a missão'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='work_other',
            field=models.BooleanField(default=False, verbose_name='Outra'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='work_other_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Outra área de atuação'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Qual(is) alergia(s)?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city_and_date',
            field=models.CharField(blank=True, max_length=120, verbose_name='Local e data'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='education',
            field=models.CharField(blank=True, max_length=180, verbose_name='Qual a sua formação ou experiência principal?'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='medication_in_use',
            field=models.TextField(blank=True, verbose_name='Nome, dosagem e horário dos medicamentos'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='special_notes',
            field=models.TextField(blank=True, verbose_name='Condições médicas relevantes ou necessidades especiais'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='work_general_help',
            field=models.BooleanField(default=False, verbose_name='Apoio geral'),
        ),
    ]
