# Generated by Django 6.0.4 on 2026-05-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_volunteer_agrees_guidelines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryDonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=180, verbose_name='Descrição da doação')),
                ('receipt', models.FileField(upload_to='comprovantes_doacoes/', verbose_name='Comprovante de doação')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_receipts', to='accounts.volunteer')),
            ],
            options={
                'verbose_name': 'Comprovante de doação',
                'verbose_name_plural': 'Comprovantes de doações',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
