# Generated by Django 6.0.4 on 2026-05-14 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_missionarydonationreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missionarydonationreceipt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conferido em'),
        ),
        migrations.AddField(
            model_name='missionarydonationreceipt',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_donation_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionarydonationreceipt',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Conferido'),
        ),
        migrations.AddField(
            model_name='panelpermission',
            name='can_review_submissions',
            field=models.BooleanField(default=False, verbose_name='Conferir documentos e comprovantes'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='documentation_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documentacao conferida em'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='documentation_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_volunteer_documentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='insurance_policy_document_confirmed',
            field=models.BooleanField(default=False, verbose_name='Apolice de seguro conferida'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='signed_registration_document_confirmed',
            field=models.BooleanField(default=False, verbose_name='Ficha assinada conferida'),
        ),
    ]
