# Generated by Django 6.0.4 on 2026-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_missionarydonationreceipt_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionarydonationreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da doação'),
        ),
    ]
