# Generated by Django 6.0.4 on 2026-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_missionarydonationreceipt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='flight_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do voo'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='flight_ticket_document',
            field=models.FileField(blank=True, upload_to='documentos/passagens/', verbose_name='Passagem aérea'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='flight_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do voo'),
        ),
    ]
