# Generated by Django 6.0.5 on 2026-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_volunteer_flight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
