# Generated by Django 6.0.5 on 2026-06-24 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_registration_force_password_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='panelpermission',
            name='can_register_expenses',
            field=models.BooleanField(default=False, verbose_name='Registrar despesas'),
        ),
    ]
