# Generated by Django 6.0.5 on 2026-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_financialtransaction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelpermission',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='Ver relatórios'),
        ),
    ]
