# Generated by Django 6.0.5 on 2026-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_panelpermission_can_view_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='vaccination_card_document',
            field=models.FileField(blank=True, upload_to='documentos/carteiras_vacinacao/', verbose_name='Carteira de vacinação'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='vaccination_card_document_confirmed',
            field=models.BooleanField(default=False, verbose_name='Carteira de vacinação conferida'),
        ),
    ]
