# Generated by Django 6.0.5 on 2026-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_volunteer_vaccination_card_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='Notificações ativadas')),
                ('provider', models.CharField(blank=True, choices=[('', 'Automático'), ('wapi', 'W-API (w-api.app)'), ('webhook', 'Webhook personalizado')], default='', max_length=10, verbose_name='Provider')),
                ('group_jid', models.CharField(blank=True, default='', max_length=100, verbose_name='JID do grupo')),
                ('default_message', models.TextField(blank=True, default='', verbose_name='Mensagem padrão')),
                ('wapi_token', models.CharField(blank=True, default='', max_length=300, verbose_name='W-API Token')),
                ('wapi_instance', models.CharField(blank=True, default='', max_length=200, verbose_name='W-API Instance ID')),
                ('wapi_base_url', models.CharField(blank=True, default='', max_length=300, verbose_name='W-API Base URL')),
                ('webhook_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Webhook URL')),
                ('webhook_token', models.CharField(blank=True, default='', max_length=300, verbose_name='Webhook Token (Bearer)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
                'verbose_name_plural': 'Configuração WhatsApp',
            },
        ),
        migrations.AddField(
            model_name='panelpermission',
            name='can_manage_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Gerenciar WhatsApp'),
        ),
    ]
