# Generated by Django 6.0.5 on 2026-06-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_whatsappconfig_panelpermission_can_manage_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('registrations', 'Inscrições'), ('financial', 'Financeiro'), ('documentation', 'Documentação'), ('general', 'Geral'), ('test', 'Teste')], max_length=32, unique=True, verbose_name='Tipo de notificação')),
                ('message_text', models.TextField(verbose_name='Mensagem')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppRecipientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Número WhatsApp')),
                ('notify_registrations', models.BooleanField(default=False, verbose_name='Inscrições')),
                ('notify_financial', models.BooleanField(default=False, verbose_name='Financeiro')),
                ('notify_documentation', models.BooleanField(default=False, verbose_name='Documentação')),
                ('notify_general', models.BooleanField(default=False, verbose_name='Geral')),
                ('notify_test', models.BooleanField(default=False, verbose_name='Teste')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_recipient_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinatário WhatsApp',
                'verbose_name_plural': 'Destinatários WhatsApp',
            },
        ),
    ]
