# Generated by Django 5.2.12 on 2026-06-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_documentation_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppConfig',
        ),
        migrations.RemoveField(
            model_name='whatsapprecipientpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='WhatsAppTemplate',
        ),
        migrations.RemoveField(
            model_name='panelpermission',
            name='can_manage_whatsapp',
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missionarydonationreceipt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='missionarypayment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='panelpermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='WhatsAppRecipientPreference',
        ),
    ]
