# Generated by Django 5.2.12 on 2026-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_financialtransaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='work_support_team',
            field=models.BooleanField(default=False, verbose_name='Equipe de apoio'),
        ),
    ]
