# Generated by Django 6.0.4 on 2026-07-17 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_volunteer_work_support_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='prestacao_contas', max_length=40, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('running', 'Gerando'), ('done', 'Concluido'), ('error', 'Erro')], default='pending', max_length=10, verbose_name='Status')),
                ('processed', models.IntegerField(default=0, verbose_name='Processados')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('phase', models.CharField(blank=True, max_length=120, verbose_name='Etapa')),
                ('file', models.FileField(blank=True, upload_to='exports_tmp/', verbose_name='Arquivo gerado')),
                ('error_message', models.CharField(blank=True, max_length=300, verbose_name='Mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportacao de PDF',
                'verbose_name_plural': 'Exportacoes de PDF',
                'ordering': ['-created_at'],
            },
        ),
    ]
